<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.14159265359"/>

  <!-- Joints Control in Gazebo -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
  </gazebo>

  <!-- Geometrical properties -->
  <xacro:property name="link_side" value="0.01"/>
  <xacro:property name="joint_radius" value="0.01"/>
  <xacro:property name="joint_length" value="0.02"/>
  <xacro:property name="toe_length" value="0.03"/>
  <xacro:property name="foot_length" value="0.04"/>
  <xacro:property name="leg_length" value="0.40"/>
  <xacro:property name="arm_length" value="0.03"/>
  <xacro:property name="hand_length" value="0.04"/>
  <xacro:property name="finger_length" value="0.03"/>

  <!-- Materials -->
  <material name="orange">
    <color rgba="1.00 0.67 0.02 1.00"/>
  </material>

  <material name="gray">
    <color rgba="0.80 0.80 0.80 1.00"/>
  </material>

  <!-- Generates a box visual/collision/inertial -->
  <xacro:macro name="prism_vci" params="side length mass:=0.5 *origin">

    <xacro:macro name="prism_geometry">
      <xacro:insert_block name="origin"/>
      <geometry>
        <box size="${side} ${side} ${length}"/>
      </geometry>
    </xacro:macro>

    <visual>
      <xacro:prism_geometry/>
      <material name="orange"/>
    </visual>

    <collision>
      <xacro:prism_geometry/>
    </collision>

    <inertial>
      <xacro:insert_block name="origin"/>
        <mass value="0.00001" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      <!-- <mass value="${mass}"/>
      <inertia ixx="${(mass/12)*(side*side+length*length)}"
               iyy="${(mass/12)*(side*side+length*length)}"
               izz="${(mass/6)*(side*side)}"
               ixy="0" ixz="0" iyz="0"/> -->
    </inertial>

  </xacro:macro>

  <!-- Generates a cylinder visual/collision -->
  <xacro:macro name="cylinder_vc" params="radius length *origin">

    <xacro:macro name="cylinder_geometry">
      <xacro:insert_block name="origin"/>
      <geometry>
        <cylinder length="${length}" radius="${radius}"/>
      </geometry>
    </xacro:macro>

    <visual>
      <xacro:cylinder_geometry/>
      <material name="gray"/>
    </visual>

    <collision>
      <xacro:cylinder_geometry/>
    </collision>

  </xacro:macro>

   <!-- Generates child joint of parent -->
  <xacro:macro name="arm_joint" params="childx childy parent dist:=0 axis">

    <joint name="${parent}_${childx}_joint" type="revolute">
      <origin xyz="0 0 ${dist}" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="${childx}"/>
      <axis xyz="1 0 0"/>
      <limit lower="-1.57"
            upper="1.57"
            effort="1000"
            velocity="2" />
    </joint>

    <!-- Required for ROS control -->
    <transmission name="${parent}_${childx}_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${parent}_${childx}_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
       <actuator name="$${parent}_${childx}_actuator">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </actuator>
    </transmission>

    <link name="${parent}">
    <xacro:prism_vci length="${dist}" side="${link_side}">
        <origin xyz="0 0 ${dist/2}" rpy="0 0 0"/>
      </xacro:prism_vci>
       <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">
      <origin xyz="0 0 ${dist}" rpy="0 ${PI/2} 0"/>
      </xacro:cylinder_vc>

      <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">
  <origin xyz="0 0 ${dist}" rpy="${PI/2} 0 0"/>

      </xacro:cylinder_vc>
    </link>



    <gazebo reference="${parent}">
      <material>Gazebo/Orange</material>
      <!-- <turnGravityoff>ture </turnGravityoff> -->
      
    </gazebo>

    <!-- yyyyyyyyyyyyyyyyyyyy -->
<joint name="${childx}_${childy}_joint" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${childx}"/>
      <child link="${childy}"/>
      <axis xyz="0 1 0"/>
      <limit  lower="-1.57"
            upper="1.57"
            effort="1000"
            velocity="2" />
    </joint>

    <!-- Required for ROS control -->
    <transmission name="${childx}_${childy}_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${childx}_${childy}_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
       <actuator name="$${childx}_${childy}_actuator">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </actuator>
    </transmission>

    <link name="${childx}">
          <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
       <mass value="0.00001" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>



    </link>

    <gazebo reference="${childx}">
      <material>Gazebo/Orange</material>
      <!-- <turnGravityoff>ture </turnGravityoff> -->
    </gazebo>


  </xacro:macro>



 
 
  <!-- World frame (for Gazebo) -->
 <!-- <link name="world">
         


    </link>

    <gazebo reference="world">
      <material>Gazebo/Orange</material>
    </gazebo>  -->

  <!-- Arm fixed to world frame  -->
  <!-- <joint name="world_foot_joint" type="revolute">
    <parent link="world"/>
    <child link="link0"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
      <limit  lower="-3.14"
            upper="3.14"
            effort="1000"
            velocity="2" />
  </joint> -->


  <!-- Joints Chain -->
   <xacro:arm_joint parent="link0" childx="link1x" childy="link1y" axis="0 0 1" dist="${arm_length}"/>
     <xacro:arm_joint parent="link1y" childx="link2x" childy="link2y" axis="0 0 1" dist="${arm_length}"/>
       <xacro:arm_joint parent="link2y" childx="link3x" childy="link3y" axis="0 0 1" dist="${arm_length}"/>
         <xacro:arm_joint parent="link3y" childx="link4x" childy="link4y" axis="0 0 1" dist="${arm_length}"/>
           <xacro:arm_joint parent="link4y" childx="link5x" childy="link5y" axis="0 0 1" dist="${arm_length}"/>
  <!-- <xacro:arm_joint parent="foot" child="leg" axis="0 1 0" dist="${foot_length}"/>
  <xacro:arm_joint parent="leg" child="arm" axis="1 0 0" dist="${leg_length}"/>
  <xacro:arm_joint parent="arm" child="hand" axis="0 0 1" dist="${arm_length}"/>
  <xacro:arm_joint parent="hand" child="finger" axis="1 0 0" dist="${hand_length}"/> -->

  <!-- End effector -->
  <link name="link5y">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.00001" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial> 
  </link>

  <gazebo reference="link5y">
    <material>Gazebo/Red</material>
  </gazebo>



</robot>