# Publish all joint states
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Control all joints
arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - link0_link1x_joint
    - link1x_link5y_joint

  gains:
    link0_link1x_joint: {p: 30,  d: 1, i: 0.1}
    link1x_link5y_joint: {p: 30,  d: 1, i: 0.1}